stages:
  - build
  - test
build:
  stage: build
  image: openjdk:12-alpine
  script:
    - ./gradlew build
  artifacts:
    paths:
      - ./build/libs/
smoke test:
  stage: test
  image: openjdk:12-alpine
  script:
    - java -jar ./build/libs/car-api.jar &
    - sleep 30
    - 